# Generated by Django 5.0 on 2024-05-07 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
