# Generated by Django 5.0 on 2024-06-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
