# Generated by Django 5.0 on 2024-06-04 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_news_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="views",
        ),
    ]
