# Generated by Django 5.0 on 2024-06-10 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_remove_news_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="active",
            new_name="is_active",
        ),
    ]
