# Generated by Django 5.0 on 2024-06-22 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hitcount", "0005_alter_blacklistip_id_alter_blacklistuseragent_id_and_more"),
        ("news", "0009_remove_news_hit_count_news_hit_count_generic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="hit_count_generic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_hit_count",
                to="hitcount.hitcount",
            ),
        ),
    ]
