# Generated by Django 5.0 on 2024-06-29 10:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0010_alter_news_hit_count_generic"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ko",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="body_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="body_ko",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="body_ru",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="body_uz",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ko",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
